name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta automáticamente una vez al día a medianoche
  push:  # Ejecuta cada vez que se hace push al repositorio
    branches: 
      - main
  workflow_dispatch: # Permite que se ejecute manualmente cuando desees

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: SHRicard # Cambia esto si tu nombre de usuario es diferente
          svg_out_path: dist/snake.svg

      - name: Deploy Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
